### ISSUE TITLE
AutoCompleteTextView to have few pre-selected items without searching but should be able to remove them as well.

### ISSUE THREAD

**Issue by rajprasad770** [cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView#1]
I've a requirement where your control works pretty fine except when I need to have few pre-selected items in the AutoCompleteTextView without searching them but I should be able to remove them as well, if required.

Now this pre-selected items are from a different list than the list which I have defined as the ItemsSource for the AutoCompleteTextView. 

However, both the lists have two common string properties - Name and ID which I'm showing after concatenation as: "Name - ID" for suggestions when user types in the AutoCompleteTextView. Also, all the entries of pre-selected items would be there in the list which is the ItemsSource of AutoCompleteTextView.

How to deal with this scenario? 

I'm thinking to create an ObservableCollection of UserList which will have only these two common string properties - Name and ID and will populate it with all the entries of the list which is the ItemsSource of AutoCompleteTextView. This way the SelectedItemSource of the AutoCompleteTextView would be UserList and then I would call SelectItem event on those items which I would like to have as pre-selected items in AutoCompleteTextView.

Will it work?

**Comment by cemozguraA** [comment]
It's unlikely this senario will be succsesfull, but i understand your point of view. I can add new properties on monday to delete pre-selected items from the ItemsSource. This will work with ObservableCollection 

Thank you for your observation.

**Comment by cemozguraA** [comment]
I did not add new properties but This work with ObservableCollection
