### ISSUE TITLE
Search List alignment issue

### ISSUE THREAD

**Issue by AbdelrhmanHamedTawfik** [cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView#11]
when trying to put the control vertical options end the applications crashes because the search list height is set to negative value 
![image](https://user-images.githubusercontent.com/57391155/74921979-35912480-53d7-11ea-99ab-ad6ac79a7667.png)

And the list should be upwards not downwards when the option is set to end

**Comment by cemozguraA** [comment]
Can you send xaml file ?

**Comment by AbdelrhmanHamedTawfik** [comment]
[AutoComp.zip](https://github.com/cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView/files/4230597/AutoComp.zip)

**Comment by cemozguraA** [comment]
![Screenshot_1582200739](https://user-images.githubusercontent.com/55392106/74932694-7d25a980-53f3-11ea-9ed7-94b16ff7e85c.png)
this is work my emulator and physical device

**Comment by AbdelrhmanHamedTawfik** [comment]
i need the list to go up not down because this way i can see only item at a time
also if do margin top till the search bar gets to the very end of the page it will give you the error

**Comment by cemozguraA** [comment]
I understand your point of view. This is version not support go up but i put list this problem

**Comment by cemozguraA** [comment]
Fixed!
