### ISSUE TITLE
Sample doesn't compile

### ISSUE THREAD

**Issue by joaogomes44033** [cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView#12]
Code behind MainPage.xaml refers a sample.Events namespace but theres none to be found. The same goes for some properties on the AutoCompleteTextView xaml, like FontSize or FontAttribute,

**Comment by cemozguraA** [comment]
can you send your demo project

**Comment by joaogomes44033** [comment]
> 
> 
> can you send your demo project

I downloaded the source code from the main branch. 
My project is the same as the AutoCompleteTextSample.

**Comment by cemozguraA** [comment]
"Xamarin.RisePlugin.AutoCompleteTextView/AutoCompleteTextSample/AutoCompleteTextSample/AutoCompleteTextSample" use this path and update your nugetpack
