### ISSUE TITLE
Set selected items from code

### ISSUE THREAD

**Issue by KyrillosS25** [cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView#5]
Is there a way to add item to SelectedItemsSource from code ?

- I have tried auto.SelectedItemsSource.Add(list[0]);
and 
SelectedItemEventArgs t = new SelectedItemEventArgs();
t.Index = 0;
t.Item = list[0];
auto.selectedItemEventArgs(t);

and managed to add item to SelectedItems but the control doesn't draw the item.

**Comment by cemozguraA** [comment]
This is view dosent not support the add selecteditems but put on the list

**Comment by KyrillosS25** [comment]
do you mean that i cannot load selected items from code ?

**Comment by cemozguraA** [comment]
You can add but not to view

**Comment by KyrillosS25** [comment]
@cemozguraA  
I know that you have done a great work creating this control but don't you think that this feature should be added ?

**Comment by cemozguraA** [comment]
next update :) will be added.

**Comment by KyrillosS25** [comment]
@cemozguraA  Thanks alot :)

**Comment by cemozguraA** [comment]
Fixed!
