### ISSUE TITLE
pre selected  items 

### ISSUE THREAD

**Issue by amr-moomen** [cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView#6]
Hello
I just wanna ask you can i add pre selected  items to AutoCompleteTextView 

i tried to add it by setting the SelectedItemsSource=new test() { Text = "Xamarin.Forms", Image ="imageurl"};
but AutoCompleteTextView  still empty

**Comment by cemozguraA** [comment]
this is not support yet next update :) will be added.

**Comment by amr-moomen** [comment]
thank you for your interest :)

**Comment by mina5500** [comment]
this would be very useful ...
when will be the next update :) @cemozguraA

**Comment by cemozguraA** [comment]
Fixed!
