### ISSUE TITLE
IOS Bug items list 

### ISSUE THREAD

**Issue by AbdelrhmanHamedTawfik** [cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView#7]
Hello, 
i noticed a small bug in the IOS if the list of item i search for is 2 items only the list becomes smaller than intended which causes some items to  be hidden see picture attached

PS: Android version is working fine

Version: 1.0.6

![image](https://user-images.githubusercontent.com/57391155/74603011-7297a700-50b7-11ea-8cd6-01ba909988e3.png)

Used project:

[AutoComp.zip](https://github.com/cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView/files/4209666/AutoComp.zip)

**Comment by cemozguraA** [comment]
pls can you open with keyboard?

**Comment by AbdelrhmanHamedTawfik** [comment]
what do you mean by open with keyboard? if you mean that i write using the simulator keyboard then it still the same problem even with the keyboard opened up 
![image](https://user-images.githubusercontent.com/57391155/74631537-df697a80-5165-11ea-8900-569baaf897f7.png)

this problem happens only when the number of filtered items are low but in the case of many items the list works fine 

![image](https://user-images.githubusercontent.com/57391155/74631620-150e6380-5166-11ea-8976-e3a3d1e33841.png)


Number of "Rise" items are 2 and number of "Xamarin" are +10

**Comment by AbdelrhmanHamedTawfik** [comment]
also you can check the issue in the attached project 
[AutoComp.zip](https://github.com/cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView/files/4212297/AutoComp.zip)

**Comment by cemozguraA** [comment]
i will check today.

**Comment by cemozguraA** [comment]
This is fixed! will get next update.
