### ISSUE TITLE
Selected item not added to AutoCompleteTextView 

### ISSUE THREAD

**Issue by amr-moomen** [cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView#9]
when update from  version 1.4 to 1.7 and select an item from the list not added to AutoCompleteTextView.

**Comment by cemozguraA** [comment]
new system work with ObservableCollection, can you look new example ?

**Comment by amr-moomen** [comment]
The new example looks like the old one 
![image](https://user-images.githubusercontent.com/56504816/74836861-edb3c400-5328-11ea-8d44-60a7fa58ae5d.png)

**Comment by cemozguraA** [comment]
https://github.com/cemozguraA/Xamarin.RisePlugin.AutoCompleteTextView/blob/master/AutoCompleteTextSample/AutoCompleteTextSample/MainPage.xaml.cs

**Comment by amr-moomen** [comment]
I replace those files and its working fine, thanks a lot.
